### PR TITLE
DLPJTS-66 - Use IoUtils.createUrlFromPath in all samples

### PR DESCRIPTION
**Pull request by datalogics-dans**
#### Changes in this pull request
- Replace all new File().toURI().toURL() calls with IoUtils.createUrlFromPath()
#### Checklist for approving this pull request

(PR creator amend this with more conditions if necessary)
- [x] There are **unit tests** for new/changed code, or a good explanation why this was not possible.
- [x] All **CI builders** have indicated success (Give them a few minutes to notice the pull request.)
- [x] The **Pull request title** has the JIRA issue numbers separated by spaces (if any), a space, and then a short, but descriptive summary.
- [x] **Commit messages** are well formed: [A note about Git commit messages](http://www.tpope.net/node/106)
- [x] New public packages, classes, and methods are **documented**. (Strongly consider documenting private classes and methods.)

### CODE REVIEW

**Comment by datalogics-dans** [comment]
@datalogics-kam Should we remove the top two items from the checklist for this repo, or are we planning on utilizing those items at some point in the near future?

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-tsmith** [comment]
@datalogics-dans based on what @datalogics-bhaugen said to me yesterday I don't think we are ever planning to update the version number so I think they can be removed.

**Comment by datalogics-dans** [comment]
Splendid! The checklist is complete, then. We should still get those items removed from the template, though I'm assuming we need an admin like @datalogics-kam (or @datalogics-bhaugen?) to do that.

**Comment by datalogics-tsmith** [comment]
:+1: looks good to me

**Comment by datalogics-kam** [comment]
> Splendid! The checklist is complete, then. We should still get those items removed from the template, though I'm assuming we need an admin like @datalogics-kam (or @datalogics-bhaugen?) to do that.

@datalogics-dans It's just a file in the `.github` directory; you can edit it and do a PR or a push just like any other file.

You could even go to https://github.com/datalogics/pdf-java-toolkit-samples/blob/develop/.github/PULL_REQUEST_TEMPLATE.md and click the little pencil icon and edit it. Just put in a reason for the changes (version numbers not applicable to this project), and it'll become the commit message.

**Comment by datalogics-bhaugen** [comment]
> @datalogics-dans based on what @datalogics-bhaugen said to me yesterday I don't think we are ever planning to update the version number so I think they can be removed.

Be careful here, what I said is that I don't believe either @datalogics-kam or I have really planned on versioning the samples, it is always a possibility though if we need to. Currently, we don't change the version of the samples (if we expect that customers might call the samples rather than calling the APIs used by the samples, then if we change how the samples function, we would want to change the version number).

**Comment by datalogics-dans** [comment]
@datalogics-kam Good to know! Template updated. We can always add that stuff back in later if we need it.

**Pull request merged**
