### PR TITLE
Updated description of PDFJT sample ImageDownsampling.java

### PR DESCRIPTION
**Pull request by datalogics-mdawson**
#### Changes in this pull request
- Wrote descriptions of the new PDFJT sample programs last spring, reviewed.
- These will not be published to the Developer's page, as they are provided through JavaDocs.
- I reviewed the sample program descriptions in PDFJT JavaDocs and offer some suggested updates.
- This is the second of a series of pull requests to offer proposed updates for eight of the sample programs.
#### Checklist for approving this pull request

(PR creator amend this with more conditions if necessary)

- [ ] There are **unit tests** for new/changed code, or a good explanation why this was not possible.
- [ ] All **CI builders** have indicated success (Give them a few minutes to notice the pull request.)
- [ ] The **Pull request title** has the JIRA issue numbers separated by spaces (if any), a space, and then a short, but descriptive summary.
- [ ] **Commit messages** are well formed: [A note about Git commit messages](http://www.tpope.net/node/106)
- [ ] New public packages, classes, and methods are **documented**. (Strongly consider documenting private classes and methods.)

#### Blockers

Add a checkbox for yourself with your **&#64;name** to this list if you are holding this PR open for review. PR Shepherd, please hold off merging this PR until these are all checked:

- [x] @datalogics-mdawson

Offer proposed new description of PDFJT sample program

Second pull request in series to update content in API Reference (JavaDocs)

Added sentence to describe downsampling process briefly

Revised content based on descriptions of sample programs
provided and reviewed in May 2016. Added to comments
in the sample Java program.

### CODE REVIEW

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-kam** [comment]
Thanks for the updates.

The builds fail due to incorrectly formatted Javadoc:

```
[WARNING] target/distributed-files/src/main/java/com/datalogics/pdf/samples/images/ImageDownsampling.java:[35] (javadoc) JavadocParagraph: Empty line should be followed by <p> tag on the next line.
[WARNING] target/distributed-files/src/main/java/com/datalogics/pdf/samples/images/ImageDownsampling.java:[38] (javadoc) JavadocParagraph: Empty line should be followed by <p> tag on the next line.
[WARNING] target/distributed-files/src/main/java/com/datalogics/pdf/samples/images/ImageDownsampling.java:[40] (javadoc) JavadocParagraph: Empty line should be followed by <p> tag on the next line.
```

``<p>`` tags are required between paragraphs in Javadoc.

Configuring Eclipse according to the information in ``CONTRIBUTING.md`` file (which was updated today; see the latest) will cause it to flag this as a warning during editing, so it's not necessary to go find the problem in the failed Jenkins build.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Pull request merged**
