### PR TITLE
DLPJTS-128 DLPJT-297 Use JDK 8, super-pom, get findbugs configuration 

### PR DESCRIPTION
**Pull request by datalogics-kam**
#### Changes in this pull request

- Use the super-pom
- This also gets the findbugs config
- Uses AdoptOpenJDK 8 for the build
- Fix up the tests
- Use Maven 3.6.3

#### Checklist for approving this pull request

(PR creator amend this with more conditions if necessary)

- [x] There are **unit tests** for new/changed code, or a good explanation why this was not possible.
- [x] All **CI builders** have indicated success (Give them a few minutes to notice the pull request.)
- [x] The **Pull request title** has the JIRA issue numbers separated by spaces (if any), a space, and then a short, but descriptive summary.
- [x] **Commit messages** are well formed: [A note about Git commit messages](http://www.tpope.net/node/106)
- [x] New public packages, classes, and methods are **documented**. (Strongly consider documenting private classes and methods.)

#### Blockers

Add a checkbox for yourself with your **&#64;name** to this list if you are holding this PR open for review. PR Shepherd, please hold off merging this PR until these are all checked:

- [x] _&lt;add your name here with an **@**>_

### CODE REVIEW

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-robl** [comment]
Question: If

1. Samples are publicly provided to customers via our public GitHub
2. Samples are dependent on our super-pom
3. Our super-pom is only available on our private Octocat GitHub

...how can customers build our samples?

**Comment by datalogics-kam** [comment]
The super-pom is in the local Maven repo we ship with PDFJT. We did consider that the samples might get ahead of what we have available. Should we use a feature branch for now?

**Comment by datalogics-robl** [comment]
I see your point: as long as they have the super-pom from their PDFJT package, they will be okay. The samples aren't useful without JT (except for prospects who might be looking at the samples to get a feel for our API--but they by definition don't have a JT release and can't build the samples); I'm not concerned with our getting a small step ahead while we work towards the next release.

**Pull request merged**
