### PR TITLE
DLPJTS-82 Link samples doc to PDFJT doc in distribution

### PR DESCRIPTION
**Pull request by datalogics-kam**
#### Changes in this pull request
- External links are created to the pdfjt-docs tree when the samples documentation appears in distribution.
- To test this, you may have to go to the `lite` directory, then do an `mvn install -Pgenerate-distribution`, then make a `pdfjt-distribution`.
#### Checklist for approving this pull request

(PR creator amend this with more conditions if necessary)
- [x] There are **unit tests** for new/changed code, or a good explanation why this was not possible.
- [x] All **CI builders** have indicated success (Give them a few minutes to notice the pull request.)
- [x] The **Pull request title** has the JIRA issue numbers separated by spaces (if any), a space, and then a short, but descriptive summary.
- [ ] **Commit messages** are well formed: [A note about Git commit messages](http://www.tpope.net/node/106)
- [x] New public packages, classes, and methods are **documented**. (Strongly consider documenting private classes and methods.)
#### Blockers

Add a checkbox for yourself with your **&#64;name** to this list if you are holding this PR open for review. PR Shepherd, please hold off merging this PR until these are all checked:
- [x] _&lt;add your name here with an **@**>_

### CODE REVIEW

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-bhaugen** [comment]
Good catch @datalogics-kam!! 🐟 🐟 🐟 🐟 (see what I did there 😃)

**Comment by datalogics-tsmith** [comment]
:+1:

**Pull request merged**
