### PR TITLE
DLPJTS-81 - Patch for README.md file

### PR DESCRIPTION
**Pull request by jrowden8**
#### Changes in this pull request
- This PR contains a patch change to add a link in the README.md file to a tutorial on using file paths in java.
#### Checklist for approving this pull request

(PR creator amends this with more conditions if necessary)
- [X] There are **unit tests** for new/changed code, or a good explanation why this was not possible.
- [x] All **CI builders** have indicated success (Give them a few minutes to notice the pull request.)
- [x] The **Pull request title** has the JIRA issue numbers separated by spaces (if any), space, and then a short, but descriptive summary.
- [x] **Commit messages** are well formed: [A note about Git commit messages](http://www.tpope.net/node/106)
- [X] New public packages, classes, and methods are **documented**. (Strongly consider documenting private classes and methods.)
#### Blockers

Add a checkbox for yourself with your **&#64;name** to this list if you are holding this PR open for review. PR Shepherd, please hold off merging this PR until these are all checked:
- [x] _&lt;add your name here with an **@**>_
- [x] @datalogics-bhaugen

### CODE REVIEW

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-kam** [comment]
@datalogics-bhaugen  Can you take a quick look at this, and perhaps I can get it merged then?

**Comment by datalogics-bhaugen** [comment]
I am okay with it, I wish Oracle had something more along the lines of what they have for the [Path](https://docs.oracle.com/javase/tutorial/essential/io/pathClass.html) class for the URL class, except I can't find anything.

**Pull request merged**
