### PR TITLE
[WIP] Specify overlay text for redaction annotations

### PR DESCRIPTION
**Pull request by datalogics-bhaugen**
Use the text “Redacted” as overlay text for redaction annotations created in the RedactAndSanitize sample to demonstrate how to set the appearance so that the overlay text does not come out black on a black rectangle.

#### Changes in this pull request

- Specify overlay text for redaction annotations
- Uses green text so that it displays well on top of a black rectangle

#### Checklist for approving this pull request

(PR creator amend this with more conditions if necessary)

- [ ] There are **unit tests** for new/changed code, or a good explanation why this was not possible.
- [ ] All **CI builders** have indicated success (Give them a few minutes to notice the pull request.)
- [ ] The **Pull request title** has the JIRA issue numbers separated by spaces (if any), a space, and then a short, but descriptive summary.
- [ ] **Commit messages** are well formed: [A note about Git commit messages](http://www.tpope.net/node/106)
- [ ] New public packages, classes, and methods are **documented**. (Strongly consider documenting private classes and methods.)

#### Blockers

Add a checkbox for yourself with your **&#64;name** to this list if you are holding this PR open for review. PR Shepherd, please hold off merging this PR until these are all checked:

- [x] _&lt;add your name here with an **@**>_

### CODE REVIEW

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-bhaugen** [comment]
Ah, thank you automated builder for pointing out to me that we **do** look at the content stream of the output document so we are testing that the PDF contains the correct content. I will update the description of this and work on updating the test.

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build failed.

**Pull request closed without merging**
