### PR TITLE
DLPJTS-88 Fix issues in samples for upcoming PDFJT release

### PR DESCRIPTION
**Pull request by datalogics-kam**
#### Changes in this pull request
- Expect different output for the FillForms test in version 4+ of the `pdfjt` artifact.
- Code to support testing with different versions of PDFJT.
#### Checklist for approving this pull request

(PR creator amend this with more conditions if necessary)
- [x] Change the Talkeetna version to `6.0.0-feature-merge-adobe-SNAPSHOT`, and the tests should still work. Verify with `mvn dependency:tree` that the Adobe changes are being pulled in.
- [x] There are **unit tests** for new/changed code, or a good explanation why this was not possible.
- [x] All **CI builders** have indicated success (Give them a few minutes to notice the pull request.)
- [x] The **Pull request title** has the JIRA issue numbers separated by spaces (if any), a space, and then a short, but descriptive summary.
- [x] **Commit messages** are well formed: [A note about Git commit messages](http://www.tpope.net/node/106)
- [x] New public packages, classes, and methods are **documented**. (Strongly consider documenting private classes and methods.)
#### Blockers

Add a checkbox for yourself with your **&#64;name** to this list if you are holding this PR open for review. PR Shepherd, please hold off merging this PR until these are all checked:
- [x] _&lt;add your name here with an **@**>_

### CODE REVIEW

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-kam** [comment]
@datalogics-robl can you take a look at this, please? Thanks!

**Comment by datalogics-robl** [comment]
2ef57ec has a typo in the comment: 'class' is misspelled.

**Comment by datalogics-robl** [comment]
Since we're using an actual Java class that's tied into the Maven machinery, does this make it significantly harder to experiment with the samples for prospects who are intentionally avoiding Maven?

ETA: After discussion with the team, we agreed that this is the best solution given our current requirements.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Pull request merged**
