### PR TITLE
DLPJTS-50 - Research document sanitization

### PR DESCRIPTION
**Pull request by datalogics-dans**
Addresses https://jira.datalogics.com/browse/DLPJTS-50

### CODE REVIEW

**Comment by datalogics-dans** [comment]
The results of this research, aside from the documentation, will be added to a new Jira card.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-dans** [comment]
@datalogics-bhaugen I created https://jira.datalogics.com/browse/DLPJT-206 for trying to fix the issue.

**Comment by datalogics-bhaugen** [comment]
Thanks @datalogics-dans!

**Comment by datalogics-tsmith** [comment]
:+1: looks good to me

**Pull request merged**
