### PR TITLE
DLPJT-193 Check XML in FillForm sample

### PR DESCRIPTION
**Pull request by datalogics-dans**
Addresses https://jira.datalogics.com/browse/DLPJT-193. Up for discussion is whether part or all of the additions to the sample should be made into PDF JT utilities.

### CODE REVIEW

**Comment by datalogics-tsmith** [comment]
The code looks good to me.

In response to the question of whether the new functions should be utilities, I would say that they probably should. As it is written the code looks like we would expect users to call them anytime they wanted to fill an XFA file, and so we should probably give the functions to them, instead of making them copy them out of the samples if they want to use them elsewhere. 

Also, would it be possible and/or sensible to take them one step further and make them things that PDFJT just automatically does as part of filling an XFA form? It seems like the user would be expected to do it manually every time, and by making it a part of the automatic part that JT does we could remove the required effort/awareness on the users' part.

**Comment by datalogics-tsmith** [comment]
Also, @datalogics-dans is this worth adding a test for?

**Comment by datalogics-dans** [comment]
My thinking is that the checks are probably okay, but having JT automatically add elements to the XML might be too much. I feel that in general, when faced with an incompatible/non-compliant file it should be up to the user to fix it, not the software. That might just be my feeling rather than standard practice, though.

And yes, you're probably right that this should have a test. Shouldn't take long to add one, so I'll get on it.

**Comment by datalogics-dans** [comment]
Since the upstream repo went public after this was opened and I changed my fork, I can't push anymore. @datalogics-tsmith, if this looks good so far, can we merge it and I'll get a PR open for the test right away?

**Comment by jrowden8** [comment]
@datalogics-dans  Just a suggestion:
You can close this PR, refork the repo, then reopen a new PR with your unit tests.

**Pull request merged**
