### PR TITLE
Test a mis-sorted POM

### PR DESCRIPTION
**Pull request by datalogics-kam**
_Don't merge this, I'm just testing something on Jenkins_

### CODE REVIEW

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-kam** [comment]
Test has served its purpose. Deleted.

**Pull request closed without merging**
