### PR TITLE
Add Maven wrapper

### PR DESCRIPTION
**Pull request by datalogics-kam**
#### Changes in this pull request
- Add maven wrapper
#### Checklist for approving this pull request

(PR creator amend this with more conditions if necessary)
- [ ] **Release notes** file has been updated as necessary. Include only _publically visible changes_. Set the first version heading to the `-SNAPSHOT` version _with no date_.
- [x] There are **unit tests** for new/changed code, or a good explanation why this was not possible.
- [x] All **CI builders** have indicated success (Give them a few minutes to notice the pull request.)
- [x] The **Pull request title** has the JIRA issue numbers separated by spaces (if any), a space, and then a short, but descriptive summary.
- [x] **Commit messages** are well formed: [A note about Git commit messages](http://www.tpope.net/node/106)
- [x] New public packages, classes, and methods are **documented**. (Strongly consider documenting private classes and methods.)
#### Blockers

Add a checkbox for yourself with your **&#64;name** to this list if you are holding this PR open for review. PR Shepherd, please hold off merging this PR until these are all checked:
- [x] _&lt;add your name here with an **@**>_

### CODE REVIEW

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-robl** [comment]
As a courtesy, could you link to the `maven-wrapper` project where you got this code?

**Comment by datalogics-kam** [comment]
We have a fork on Octocat.

**Comment by datalogics-kam** [comment]
Sorry, it's in our GitHub organization, it's a fork of a public project.

**Comment by datalogics-robl** [comment]
Perhaps we should mention the use of `maven-wrapper` in the README?

**Comment by datalogics-kam** [comment]
I've got a task item to go and update the README files on all of our PDFJT projects already.

**Pull request merged**
