### PR TITLE
DLPJTS-81 Update documentation to explain support for remote files with samples

### PR DESCRIPTION
**Pull request by jrowden8**
#### Changes in this pull request
- This PR contains a modification to the READE.md file to explain using remote files with samples.
#### Checklist for approving this pull request

(PR creator amend this with more conditions if necessary)
- [ ] There are **unit tests** for new/changed code, or a good explanation why this was not possible.
- [ ] All **CI builders** have indicated success (Give them a few minutes to notice the pull request.)
- [ ] The **Pull request title** has the JIRA issue numbers separated by spaces (if any), a space, and then a short, but descriptive summary.
- [ ] **Commit messages** are well formed: [A note about Git commit messages](http://www.tpope.net/node/106)
- [ ] New public packages, classes, and methods are **documented**. (Strongly consider documenting private classes and methods.)
#### Blockers

Add a checkbox for yourself with your **&#64;name** to this list if you are holding this PR open for review. PR Shepherd, please hold off merging this PR until these are all checked:
- [x] _&lt;add your name here with an **@**>_

### CODE REVIEW

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-tsmith** [comment]
:+1: looks good to me

**Comment by jrowden8** [comment]
Thanks @datalogics-tsmith !

**Pull request merged**
