### PR TITLE
Updated description of PDFJT sample SignDocument.java

### PR DESCRIPTION
**Pull request by datalogics-mdawson**
#### Changes in this pull request

- Wrote descriptions of the new PDFJT sample programs last spring, reviewed.
- These will not be published to the Developer's page, as they are provided through JavaDocs.
- I reviewed the sample program descriptions in PDFJT JavaDocs and offer some suggested updates.
- This is the final pull request in this series to offer proposed updates for eight of the sample programs.

#### Checklist for approving this pull request

(PR creator amend this with more conditions if necessary)

- [ ] There are **unit tests** for new/changed code, or a good explanation why this was not possible.
- [ ] All **CI builders** have indicated success (Give them a few minutes to notice the pull request.)
- [ ] The **Pull request title** has the JIRA issue numbers separated by spaces (if any), a space, and then a short, but descriptive summary.
- [ ] **Commit messages** are well formed: [A note about Git commit messages](http://www.tpope.net/node/106)
- [ ] New public packages, classes, and methods are **documented**. (Strongly consider documenting private classes and methods.)

#### Blockers

Add a checkbox for yourself with your **&#64;name** to this list if you are holding this PR open for review. PR Shepherd, please hold off merging this PR until these are all checked:

- [x] _@datalogics-mdawson_

Eighth and final pull request in series to update content in API Reference

Proposed description of PDFJT sample program

Expanded discussion of the certificate file

### CODE REVIEW

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-devauto** [comment]
Build failed.

**Comment by datalogics-mdawson** [comment]
I can't determine from Jenkins why the build failed.

**Comment by datalogics-robl** [comment]
@datalogics-mdawson Try looking at the "Console Output" link on the left side of the Jenkins screen. It looks like you have a non UTF-8 character in your comment, probably a single-quote got auto converted into an apostrophe and Eclipse isn't configured to save as UTF-8.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Comment by datalogics-devauto** [comment]
Build succeeded.

**Pull request merged**
